### PR TITLE
fix(server): Cannot read property 'accept-version' of undefined

### LINKED ISSUE #144: Cannot read property `accept-version` when changing column from array to non-array
- [x] Repro

### PR DESCRIPTION
**Pull request by soedirgo**
## What kind of change does this PR introduce?

Bug fix.

## What is the current behavior?

Some failing requests are returning cryptic `Cannot read property 'accept-version' of undefined` error.

## What is the new behavior?

Sayonara cryptic errors. Responses should now provide the *actual* errors.

## Additional context

Closes #144.
Related: https://github.com/supabase/supabase/issues/2404#issuecomment-913153702

### CODE REVIEW

File: src/server/routes/tables.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default async (fastify: FastifyInstance) => {
     const { data, error } = await pgMeta.tables.retrieve({ id })
     await pgMeta.end()
     if (error) {
-      request.log.error({ error, req: request.body })
+      request.log.error(JSON.stringify({ error, req: request.body }))
```
Comment (darora) [inline src/server/routes/tables.ts:40]: This...fixes the response sent back to the client?

Comment (soedirgo) [reply src/server/routes/tables.ts:40]: Ostensibly yeah, `request.log.error` accepts a string, not sure what the handler does but once I pass it an object all bets are off

Comment (soedirgo) [reply src/server/routes/tables.ts:40]: Not sure where the `accept-version` stuff comes from.

Comment (soedirgo) [reply src/server/routes/tables.ts:40]: Interesting, in fact setting `req` to anything triggers the error. Doesn't happen when I set e.g. `a`. Not sure why that matters.

Comment (inian) [reply src/server/routes/tables.ts:40]: Ahh makes sense now. I think fastify sets that key and that key is overriden by you here. So the internal logging module is trying to do req.headers.accept-version and that ends up throwing the error.

Comment (soedirgo) [reply src/server/routes/tables.ts:40]: `JSON.stringify`ing `request.body` seems fine. Either way simply passing a string as per docs seems to have fixed it, so probably not worth it to go further down the rabbit hole.

**Review by darora — APPROVED** [review]
